apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: assisted-service
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gbenhaim-tenant/assisted-service/assisted-service@sha256:edb75642a3cf1a5084ff04f2cc61fac764a2c1c75cb28706ffa3c967f4491a68
        name: my-python
        resources: {}
status: {}
